# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

lane :build do
    gym
    notarize({
        package: "Fileaway.app",
        username: ENV['APPLE_DEVELOPER_ID'],
    })
    zip(
        path: "Fileaway.app",
        output_path: "Fileaway.app.zip"
    )
end
