# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

skip_docs

keychain_path = Pathname.new(File.join(Dir.pwd, "..", "temporary.keychain")).cleanpath.to_s
puts(keychain_path)

lane :init_keychain do

    File.delete(keychain_path) if File.exist?(keychain_path)
    sh(
        "security", "create-keychain",
        "-p", ENV['TEMPORARY_KEYCHAIN_PASSWORD'],
        keychain_path
    )
    sh(
        "security", "set-keychain-settings",
        "-lut", "21600",
        keychain_path
    )
    import_certificates

end

lane :import_certificates do
    # In theory, this will create the keys and download them if necessary.
    # Failing because it somehow maps a Developer ID Application key to AppStore by mistake.
    # We do this in a separate lane to ensure it doesn't taint our build (which is working fine, thank you very much).
    sync_code_signing(
        storage_mode: "git",
        git_url: ENV['CERTIFICATE_REPOSITORY'],
        git_basic_authorization: ENV['CERTIFICATE_REPOSITORY_AUTHORIZATION_KEY'],
        type: "developer_id",
        app_identifier: "uk.co.inseven.fileaway",
        readonly: true,
        skip_provisioning_profiles: true,
        keychain_name: keychain_path,
        keychain_password: ENV['TEMPORARY_KEYCHAIN_PASSWORD'],
    )
end

lane :release do

    # TODO: Read the target name.

    output_directory = "builds"
    output_name = "Fileaway"
    target = File.join(output_directory, output_name + ".app")
    version_number = get_version_number(
        xcodeproj: "macos/Fileaway-macOS.xcodeproj",
        target: "Fileaway"
    )
    commit = last_git_commit
    commit_fingerprint = commit[:abbreviated_commit_hash]
    build_number = commit_fingerprint.upcase + "." + Time.now.to_i.to_s
    zip_basename = output_name + "-macOS-" + version_number + "-" + build_number + ".zip"
    zip_path = File.join(output_directory, zip_basename)

    sh("security", "unlock-keychain", "-p", ENV['TEMPORARY_KEYCHAIN_PASSWORD'], keychain_path)
    sh("security", "list-keychain", "-d", "user", "-s", keychain_path)

    build_app(
        scheme: "Fileaway macOS",
        output_directory: output_directory,
        output_name: output_name,
        export_options: {
            method: "developer-id",
            teamID: ENV['APPLE_TEAM_ID']
        },
        xcargs: "BUILD_NUMBER='%{build_number}' OTHER_CODE_SIGN_FLAGS='--keychain=\"%{keychain_path}\"'" % {build_number: build_number, keychain_path: keychain_path}
    )
    notarize(
        package: target,
        username: ENV['APPLE_DEVELOPER_ID'],
        verbose: true,
    )
    zip(
        path: target,
        output_path: zip_path
    )

end

lane :test do
    sh("../scripts/test.sh")
end
