title: Fileaway
email: support@jbmorley.co.uk
description: ""
url: "https://fileaway.app"
baseurl: ""
twitter_username: jekyllrb
github_username:  jekyll

plugins:
  - jekyll-feed
destination: ../_site

defaults:
  - values:
      layout: "default"
