name: update-release-notes

on:
  schedule:
    - cron:  '0 1 * * *'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  run:

    runs-on: macos-ventura

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
        ref: main

    - name: Install dependencies
      run: scripts/install-dependencies.sh

    - name: Update release notes
      run: |
        scripts/update-releases.sh

    - name: Commit documentation
      uses: stefanzweifel/git-auto-commit-action@v4
      id: auto-commit
      with:
        commit_message: "docs: Update release notes"
